### ISSUE TITLE
a stupid question...

### ISSUE THREAD

**Issue by hoyqliao** [picturae/openseadragonselection#12]
so sorry i'm new studying javascript. i still couldn't understand how to use the plugin directly.
T^T
after Include dist/openseadragonselection.js, I only need to add "var selection = viewer.selection(options);"  to my code, then "set selection.enable();"
is that correct?(coz i just couldn't get it.T^T)

**Comment by danielsmink** [comment]
You first have to create the viewer.

For an example you can view our demo page.
http://picturae.github.io/ and specifically the JS part:
http://picturae.github.io/openseadragonselection/javascripts/main.js

**Comment by hoyqliao** [comment]
thxxxx!
