### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hoyqliao** [picturae/openseadragonselection#13]
sorry, coming again. i still couldn't make it...
the thing is, i've already got a view in my project, and it goes well in basic functions. 
then i add openseadragonselection.js to my html, and set selection.enable()(not sure if that's right).
PLZ tell me what should i do next...
For now i don't need to show the RGB & ZoomLevels beside the viewer like the demo does.

**Comment by MindFreeze** [comment]
The very least you need to do is: once you have the `viewer´ object, call ´viewer.selection()´.
You can pass an options object to that, which can contain a function to be called when a selection is made. Again, please check out the code on the demo page.

**Comment by hoyqliao** [comment]
thx sooo much!!!! it's initiated now. new problem is that i couldn't drag to adjust the size of the selected area... just  a tiny fixed area...
