### ISSUE TITLE
openseadragonselection and svg-overlay combined

### ISSUE THREAD

**Issue by DanielMekotron** [picturae/openseadragonselection#14]
Hi,

I have some issues using both svg-overlay and openseadragonselection at the same time.

If i do not use the svg-overlay, the selection works fine, but when i enable the svg-overlay i can no longer use the selection.

Any hints on how I can get both svg-overlay and openseadragonselection to work at the same time?

Best Regards
Daniel

**Comment by DanielMekotron** [comment]
iangilman assisted adn solved it by adding:
$(viewer.canvas).find('svg').css('pointer-events', 'none');

**Comment by danielsmink** [comment]
Good to hear, sorry for not responding it's a busy period at the office!
