### ISSUE TITLE
on selection Enable callback

### ISSUE THREAD

**Issue by rubystars** [picturae/openseadragonselection#16]
I'd like to respond to the on selection Enable callback (when the user clicks the selection button) , is there an event I can respond to? 

Thanks

**Comment by MindFreeze** [comment]
The plugin does:
`this.viewer.raiseEvent('selection_toggle', {enabled: enabled});`
So you can subscribe to the 'selection_toggle' event on the viewer and check the 'enabled' property in the event data.

**Comment by rubystars** [comment]
Thanks for the quick response, that should work :-)
