### ISSUE TITLE
Rendering saved selection data; rotation does not apply through viewer.addOverlay

### ISSUE THREAD

**Issue by QwisoDev** [picturae/openseadragonselection#17]
I figured I would ask here first, since you write a class to deal with rotation on the overlay. I have saved all the relevant data from the onSelection callback, including rotation. I'm having issues rendering them back with rotation being applied. For now I just use viewer.addOverlay which I know doesn't consider rotation

Is there an easy way to instantiate a static SelectionOverlay so it will hook all of the onDraw or onHtml methods?

**Comment by MindFreeze** [comment]
I don't know about easy but you can create an overlay and redraw it on relevant events.
I haven't tested this code, but this is a simplification of the code in this repo:
```
var div = $.makeNeutralElement('div');
div.className = 'custom-overlay';
var overlay = new $.SelectionOverlay(div, new $.SelectionRect(/* position data here */));
function draw() { 
  overlay.drawHTML(viewer.drawer.container, viewer.viewport); 
}
viewer.addHandler('open', draw);
viewer.addHandler('animation', draw);
viewer.addHandler('resize', draw);
viewer.addHandler('rotate', draw);
```
where `$ = OpenSeadragon` and `viewer` is your viewer object.

**Comment by QwisoDev** [comment]
Thanks for the reply. I did end up getting my desired effects by adding the rotation to the dataset of each element. I chose this route because rotation of the viewer is not something I will allow and $.Overlay has the logic to apply rotation based on the viewport rotation. I added code to check for my dataset entry and apply that instead

myscript.js:
```
var element = document.createElement("div");    
element.className = "openseadragon-overlay";  
element.dataset.rotation = selectBox.rotation; // my object  

var location = viewer.viewport.imageToViewportRectangle(new OpenSeadragon.Rect(selectBox.x, selectBox.y, selectBox.width, selectBox.height);  

viewer.addOverlay(element, location);
```

then updated this bit of `overlay.js:259` 

from
```
var rotate = positionAndSize.rotate;
```
to
```
var rotate = (typeof element.dataset.rotation != "undefined") ? element.dataset.rotation : positionAndSize.rotate;
```

---------------

I tested your code and it did work as well. Had to access the classes using `OpenSeadragon.SelectionOverlay` and `OpenSeadragon.SlectionRect`
