### ISSUE TITLE
Using in React

### ISSUE THREAD

**Issue by LiguidCool** [picturae/openseadragonselection#22]
Hi, How i can use plugin in React?
If I get right, OpenSeaDregon loads like AMD module, but plugin cant this?

**Comment by MindFreeze** [comment]
I honestly have no idea. This is a question for OpenSeaDragon because it affects all plugins in general.
The way plugins are created now, they assume a global object called `OpenSeaDragon`

**Comment by LiguidCool** [comment]
I find answer: 
`import OpenSeaDragon from 'openseadragon';
import OpenSeadragonSelection from 'openseadragonselection/dist/openseadragonselection.js';
...
OpenSeaDragon.selection = OpenSeadragonSelection;
`
and use it ...

**Comment by lk-jeffpeck** [comment]
Has anyone been able to get this to work?
