### ISSUE TITLE
Please add some default images for selection_confirm_pressed.png etc.

### ISSUE THREAD

**Issue by macarthy** [picturae/openseadragonselection#4]
Hi,

Thanks for working on this, looks interesting. I'm trying it out and I noticed that there are no images for 

selection_hover.png
selection_pressed.png
selection_confirm_rest.png
selection_confirm_hover.png
selection_confirm_grouphover.png
selection_confirm_pressed.png 
selection_cancel_rest.png
selection_cancel_grouphover.png
selection_cancel_pressed.png 
selection_cancel_hover.png

in the repo. Could you consider posting some?  

This could be a very helpful plugin. 

Thanks

**Comment by MindFreeze** [comment]
done https://github.com/picturae/openseadragonselection/commit/06488095e43500e980e7d23dc29dec1ee0048693
They are not really used yet, but that is for another issue
