### ISSUE TITLE
Selection confirm and cancel labels are always the same

### ISSUE THREAD

**Issue by gjactat** [picturae/openseadragonselection#41]
Hello,
I've noticed that the titles of the two buttons displayed over the selection (confirm/cancel) are always the same, despite being properly initialized with distinct values.

This problem can be observed on the test page (both buttons have th 'Ok' label) : https://picturae.github.io/openseadragonselection/

**Comment by MindFreeze** [comment]
On the demo page only the 'confirm' button has a specified tooltip with
`OpenSeadragon.setString('Tooltips.SelectionConfirm','Ok');`

**Comment by gjactat** [comment]
Thanks for your reply.
I've built a tiny CodePen to show you what happens when you specify both "SelectionConfirm" and "SelectionCancel". As you can see, both buttons get the same label eventually : https://codepen.io/gjactat/pen/NoaPbm

**Comment by MindFreeze** [comment]
I see the problem. The minified version in `/dist` was built from very old code. I just compiled it with the latest changes so it works now. Just remember to clear your cache.

**Comment by gjactat** [comment]
Thanks !
One more question : Is there an official npm package of this plugin ? The one I use was updated for years ago... https://www.npmjs.com/package/openseadragonselection
