### ISSUE TITLE
Enabling selection mode

### ISSUE THREAD

**Issue by davepruitt** [picturae/openseadragonselection#6]
Is there a way to enable selection mode without using your built-in selection control or the keyboard shortcut? 

I have a button on my page, completely separate from anything openseadragon-related, and I want to make it so that the button callback initiates "selection mode".

**Comment by MindFreeze** [comment]
Yes. You can pass a dom element or id to the `toggleButton` option. But you will have to manage its appearance, like active state. And you can check if selection is enabled with `selection.isSelecting`

**Comment by MindFreeze** [comment]
You can also pass `showSelectionControl: false` and implement your own event handling by calling `selection.enable()`, `selection.disable()` or `selection.toggleState()` . And you can change the key shortcut by adjusting `keyboardShortcut` or set it to false|null to disable it.
