### ISSUE TITLE
Convert Openseadragon overlay to selection

### ISSUE THREAD

**Issue by SuneRadich** [picturae/openseadragonselection#9]
I am still learning to navigate in openseadragon and your selection plugin, is there any built in functionality to convert a openseadragon overlay to a selection?

Currently I create a normal overlay in the `onSelection` function of a selection, to create an overlay in the area selected. But I want to be able to convert back to the selection, to let the user adjust the selection they previously made. Are there any built in stuff I can use, or do I need to calculate the x,y, width and height properties based on the DOM element myself?

**Comment by MindFreeze** [comment]
Currently there is nothing for this. If you have the OpenSeadragon.Overlay object, if has a `.location` property that is basically a rectangle with the coordinates. You can assign that to `selection.rect` and call `selection.draw()`. I have not tested this but it should work.
